"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING
from dev_utils.sqlalchemy.profiling.containers import QueryInfo

if TYPE_CHECKING: ...

def pretty_query_info(info: QueryInfo | Sequence[QueryInfo]) -> str:
    """Pretty text from QueryInfo.

    Make string from information to log it.
    """
    ...
