class BaseDevError(Exception): ...
class NoDeclarativeModelError(BaseDevError): ...
class NoModelAttributeError(BaseDevError): ...
class NoModelRelationshipError(NoModelAttributeError): ...
class FilterError(BaseDevError): ...
class ProfilingError(BaseDevError): ...
