from collections.abc import Sequence
from typing import Any, TypeGuard

def all_dict_keys_are_str(value: dict[Any, Any]) -> TypeGuard[dict[str, Any]]: ...
def all_elements_in_sequence_are_str(value: Sequence[Any]) -> TypeGuard[Sequence[str]]: ...
